version: '3'
services:
  grafana:
    image: grafana/grafana
    network_mode: host
    working_dir: /work
    user: root
    environment:
    - GF_PATHS_DATA=grafana
    - GF_PATHS_CONFIG=grafana.ini
    volumes:
    - .:/work
  prometheus:
    image: prom/prometheus
    network_mode: host
    working_dir: /work
    entrypoint:
    - /bin/sh
    command:
    - -c
    - prometheus --storage.tsdb.path=prometheus --config.file=prometheus.yml --web.listen-address=0.0.0.0:9090 --web.external-url=https://k0s.io/prometheus --web.route-prefix=/prometheus
    volumes:
    - .:/work
# prometheus-endpoint-updater:
#   image: latestarch/linux
#   network_mode: host
#   working_dir: /work
#   entrypoint:
#   - /bin/bash
#   command:
#   - -c
#   - "./update_scrape_targets"
#   volumes:
#   - .:/work
